server:
  port: 8001
spring:
  application:
    name: spring-cloud-bus-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ThomaWh/SpringCloud.git #仓库地址
          search-paths: config-repo #对应仓库相对路径,可以配置多个用","分割
          username: ThomaWh
          password: wang961226
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   # 注册中心eurka地址

management:
  security:
    enabled: false